# Generated by Django 5.0.1 on 2024-03-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('genres', models.TextField()),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMovie',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.TextField()),
                ('age', models.IntegerField()),
                ('occupation', models.IntegerField()),
                ('zipcode', models.TextField()),
                ('age_desc', models.TextField(blank=True, null=True)),
                ('occ_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_movie',
                'managed': False,
            },
        ),
    ]
