# Generated by Django 4.2.10 on 2024-03-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usermovie',
            options={},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.movie'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.usermovie'),
        ),
    ]
